#!/bin/bash
#
# Taho Script
#
# Executes a Taho command

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck disable=SC2001
# shellcheck disable=SC2016
# shellcheck disable=SC2059
# shellcheck disable=SC2116
# shellcheck disable=SC2126

# Setup colors
c0='\033[0m'    # No color
c1='\033[0;32m' # Green
c2='\033[0;31m' # Red

# We need Terragrunt to be non interactive.
export TG_NON_INTERACTIVE=true

dkr() {  
  local taho_id
  taho_id="$(uuidgen)"

  # Use linux/amd64
  export DOCKER_DEFAULT_PLATFORM='linux/amd64'

  # Capture the current working directory
  local working_dir="$PWD"

  # Change directory to toplevel
  cd "$(git rev-parse --show-toplevel)" || exit 1

  # Build
  if [[ "$1" == '-V' ]]; then
    export TAHO_VERBOSE=true
    shift
  fi
  (
    cd "$TAHO_HOME" || exit 1
    db="docker build . -t taho"
    if [ -z "$TAHO_VERBOSE" ]; then
      db+=' > /dev/null 2>&1'
    fi
    eval "$db"
  )

  # Create a .git/sre directory and use it to define the startup script. The
  # startup script allows us to preserve the working directory.
  mkdir -p .tmp
  (
    echo $'#!/bin/bash\n'
    echo "cd '.$(
      echo "$working_dir" |
      sed 's/'"$(
        pwd |
        sed 's/\//\\\//g'
      )"'//'
    )'"
    echo 'export PATH="$HOME/.tfenv/bin:$PATH"'
    echo 'export PATH="$HOME/.tgenv/bin:$PATH"'
    echo 'export PATH="$HOME/go/bin:$PATH"'
    if [ -z "$1" ]; then
      echo 'bash'
    else
      echo "bash -c 'source /root/.bashrc; $*'"
    fi
  ) > ".tmp/start-$taho_id"
  chmod +x ".tmp/start-$taho_id"

  # Ensure that required file system resources exist.
  existing_or "$HOME/.cache/pre-commit"         'mkdir -p'
  existing_or "$HOME/.terraform.d/plugin-cache" 'mkdir -p'
  existing_or "$HOME/.terraformrc"              'touch'
  existing_or "$PWD/.tmp/history"               'touch'

  # Create a docker command
  local d
  d='docker run --rm -it'
  d+=' -e TAHO_DOCKER=true'
  d+=" -h '$(basename "$PWD")'"
  d+=" -v '$HOME/.ssh:/root/.ssh'"
  d+=" -v '$PWD:/workspace'"
  d+=" -v '$PWD/.tmp/history:/root/.history:rw'"

  # Add volume mounts to the docker command
  for x in \
    '.cache/pre-commit' \
    '.ssh/known_hosts' \
    '.gitconfig'
  do
    d+=" -v '$HOME/$x:/root/$x'"
  done

  # Add rw volume mounts to the docker command
  for x in \
    '.terraform.d/plugin-cache' \
    '.terraformrc' \
    '.aws'
  do
    d+=" -v '$HOME/$x:/root/$x:rw'"
  done

  # Add environment variables to the docker command
  for v in $(
    env |
    grep -E '^(AWS_)' |
    sed 's/=.*//' \
  ); do
    d+=" -e $v"
  done

  # Evaluate the docker command
  eval "$d taho './.tmp/start-$taho_id'"
}

# Define a function for exist or evaluate
existing_or() {
  [ -e "$1" ] || eval "$2 $1"
}

#######################################
# Echo Reverse
# Arguments:
#   $1 - String with lines to reverse.
# Returns
#   0 if successfully, non-zero on error.
#######################################
echo_reverse() {
  local line result nl
  nl=$'\n'
  for line in $(echo "$1"); do
    result="${line}${nl}${result}"
  done
  echo "$result"
}

#######################################
# Process a unit directory
# Arguments:
#   TBD
# Returns
#   0 if successfully, non-zero on error.
#######################################
process_unit() {
  local cmd cmd1 drift enabled n unit
  n="$1"; shift
  count="$1"; shift
  cmd="$1"; shift
  unit="$1"; shift

  if [ -n "$unit" ]; then
    (
      # Set AWS REGION based on unit directory
      AWS_REGION="$(echo "$unit" | sed 's/\/.*//')"
      export AWS_REGION

      # The parent may or may not be based on $AWS_ALIAS.
      local parent
      if [ -n "$TAHO_ALIAS_ROOT" ]; then
        parent="infrastructure/$AWS_ALIAS"
      else
        parent="infrastructure"
      fi

      if ! cd "$parent/$unit"; then
        echo -e "${c2}Could not change directory to '$unit'${c0}" >&2
        exit 1
      fi

      # If a clean was reqeusted remove cache directories
      if [[ "$1" == 'clean' ]]; then
        rm -rf .terraform .terragrunt-cache
      fi

      mkdir -p .terragrunt-cache

      # Process cmd (level 1)
      cmd1="$cmd"
      case "$cmd1" in
        apply)
          echo -e "\n* PWD: $(pwd)"
          tg_run 'apply' "$unit" "$@"
          ;;
        check)
          if \
            terragrunt plan -detailed-exitcode -lock=false \
            > .terragrunt-cache/output 2>&1
          then
            drift='false'
          else
            drift='true'
          fi
          ;;
        destroy)
          echo -e "\n* PWD: $(pwd)"
          tg_unit_enabled "$unit" false
          cmd="$1"; shift
          if [[ "$cmd" == '-auto-approve' ]]; then
            terragrunt destroy -auto-approve
            rm -rf .terragrunt-cache
          else
            terragrunt destroy
          fi
          ;;
        disable)
          tg_unit_enabled "$unit" false
          cmd="$1"; shift
          if [[ "$cmd" == 'apply' ]]; then
            cmd1=''
            tg_run 'apply' "$unit" "$@"
          fi
          ;;
        enable)
          tg_unit_enabled "$unit" true
          cmd="$1"; shift
          if [[ "$cmd" == 'apply' ]]; then
            cmd1=''
            tg_run 'apply' "$unit" "$@"
          fi
          ;;
        init)
          echo -e "\n* PWD: $(pwd)"
          tg_run 'init' "$unit" "$@"
          ;;
      esac

      # Process cmd (level 2)
      case "$cmd1" in
        check|disable|enable|ls)
          tg_line "$n" "$count" "$drift" "$unit"
          ;;
      esac
    )
  fi
}

#######################################
# Terragrunt Apply
# Arguments:
#   $@ - Subcommands (i.e. -upgrade, or -auto-approve)
# Returns
#   0 if successfully, non-zero on error.
#######################################
tg_run() {
  local cmd
  cmd="$1"; shift

  local unit="$1"; shift

  if [[ "$1" == '-upgrade' ]]; then
    shift
    rm -rf .terragrunt-cache
    time terragrunt init -upgrade
  else
    time terragrunt init
  fi

  if [[ "$cmd" == 'apply' ]]; then

    if [[ "$1" != '-auto-approve' ]]; then
      terragrunt apply
    else
      shift
      time terragrunt apply -auto-approve

      # Handle the special case of applying vpc-endpoints where on the initial
      # apply we need to apply again to get the output.
      #
      # This logic requires a path that contains "/vpce/".
      if [[ "$unit" =~ .*\/vpce\/.* ]]; then
        local dns_entry
        dns_entry="$(terragrunt output -json | jq '.dns_entry.value')"
        if [[ "$dns_entry" == '[]' ]]; then
          echo "Running 2nd apply for VPC-Endpoint with empty dns_entry"
          time terragrunt apply -auto-approve
        else
          echo 'Not running 2nd apply for VPC-Endpoint with' $'\n' "$dns_entry"
        fi

      fi

    fi

  fi
}

#######################################
# Show the unit enable state
# Arguments:
#   *
# Returns
#   0 if successfully, non-zero on error.
#######################################
tg_line() {
  local n="$1"; shift
  local count="$1"; shift
  local drift="$1"; shift
  local unit="$1"; shift

  local count_color="${c0}"
  local drift_color="${c0}"
  local enabled_color="${c0}"
  local module_color="${c0}"
  local ref_color="${c0}"
  local unit_color="${c0}"

  local enabled
  enabled="$(
    grep -E 'unit *= ' terragrunt.hcl |
    sed 's/.*= //' |
    sed 's/ .*//'
  )"

  if [[ "$enabled" == 'true' ]]; then
    enabled_color="${c1}"
    unit_color="${c1}"
    enabled='yes'
  else
    enabled=''
  fi

  if [[ "$drift" == 'true' ]]; then

    # Show the state (empty or really empty) means this is a new state.
    local show
    show="$(terragrunt show -json 2> /dev/null)"
    if [[ "$show" == '{"format_version":"1.0"}' ]]; then
      show=''
    fi

    if [[ "$show" == '' ]]
    then
      drift='new'
    else
      drift='yes'
      drift_color="${c2}"
      enabled_color="${c2}"
      unit_color="${c2}"
    fi
  else
    drift=''
  fi

  local source
  source="$(
    grep -F 'source =' terragrunt.hcl |
    sed 's/.*://' |
    sed 's/"//'
  )"

  local module
  module="$(
    echo "$source" |
    sed 's/^pearson-digitalandtechnology\/identity-idam-gsc-modules\/\///'
  )"

  # Trim source
  source="$(
    echo "$source" |
    sed 's/.*\/\///' |
    sed 's/\?ref=.*//'
  )"

  local ref
  ref="$(echo "$module" |
  sed 's/.*\?ref=//')"

  local behind best_version latest_version note

  # If we have a version tag are we using the latest version?
  if [[ "$(
    find .terragrunt-cache -name .git -type d |
    tail -n 1 |
    wc -l
  )" == '1' ]]; then
    if [[ "$ref" =~ ^v[0-9].* ]]; then
      local tg_dir
      tg_dir="$(
        find .terragrunt-cache -name .git -type d |
        tail -n 1
      )"

      behind="$(
        cd "$tg_dir" || exit 1
        cd "../$source" || exit 1
        git log --oneline "$ref"..origin/main -- .| wc -l
      )"

      latest_version="$(
        cd "$tg_dir" || exit 1
        cd "../$source" || exit 1
        git describe origin/main
      )"

      if [[ "$behind" != '0' ]]; then
        ref_color="${c2}"
        if [[ "$behind" != "$latest_version" ]]; then
          note+=" behind=$behind"
        fi
      fi

      for t in $(
        cd "$tg_dir" || exit 1
        cd "../$source" || exit 1
        git tag | grep -E '^v' | sort -V -r
      )
      do
        if [[ "$(
          cd "$tg_dir" || exit 1
          cd "../$source" || exit 1
          git log --oneline "$t"..origin/main -- . | wc -l
        )" != '0' ]]; then
          break
        fi
        best_version="$t"
      done

      if [[ "$ref" != "$best_version" ]]; then
        note+=" best=$best_version"
      fi
    fi
  fi

  if [[ "$ref" == "$best_version" ]]; then
    ref_color="${c1}"
  fi

  module="$(echo "$module" |
  sed 's/\?ref=.*//')"

  if [ -n "$TABLE_COLS" ]; then
    local spec=''
    spec="|${count_color}%5s${c0}|"
    spec+="${enabled_color}%-3s${c0}|"
    spec+="${drift_color}%-3s${c0}|"
    spec+="${unit_color}%-36s${c0}|"
    spec+="${module_color}%-15s${c0}|"
    spec+="${ref_color}%11s${c0}|"
    spec+="$note\n"

    printf "$spec" "$n/$count" "$enabled" "$drift" "$unit" "$module" "$ref"
  else
    local spec=''
    spec="|${count_color}%5s${c0}|"
    spec+="${drift_color}%-3s${c0}|"
    spec+="${unit_color}%-68s${c0}|"
    spec+="$note\n"

    printf "$spec" "$n/$count" "$drift" "$unit"
  fi
}

#######################################
# Set the unit enable state
# Arguments:
#   $1 Unit path
#   $2 Value (true or false)
# Returns
#   0 if successfully, non-zero on error.
#######################################
tg_unit_enabled() {
  local unit="$1"; shift
  local enabled="$1"; shift

  local sed_cfg
  sed_cfg="s/ *unit * = \{ enabled = .* \}/unit = { enabled = $enabled }/g"

  sed -i -r "$sed_cfg" terragrunt.hcl;
  taho > /dev/null
}

#######################################
# Main function
# Arguments:
#   $@ Subcommand (i.e. check, destroy, disable, or enable)
# Returns
#   0 if successfully, non-zero on error.
#######################################
main() {
  if [ -z "$TAHO_HOME" ]; then
    # shellcheck disable=SC2012
    TAHO_HOME="$(
      ls -lap "$(which taho)" |
      sed 's/.*> //' |
      sed 's/\/script$//'
    )"
  fi
  export TAHO_HOME


  # Parse the command
  local cmd
  cmd="${1:-check}"; shift
  if [[ "$cmd" == 'install' ]]; then
    rm -rf /usr/local/bin/taho
    ln -s "$PWD/script" /usr/local/bin/taho
    go install
    echo 'Installed taho'
    exit
  fi

  # Make sure .tmp exists
  mkdir -p .tmp

  # Process command (top level)
  local e environment filter n
  case "$cmd" in
    -v)
      taho-go -v
      exit
      ;;
    apply|check|enable|init|ls)
      e='echo'
      ;;
    clean)
      cd "$(git rev-parse --show-toplevel)" || exit 1
      find . -name ".terraform" -type d -exec rm -rf "{}" \; &> /dev/null
      find . -name ".terragrunt-cache" -type d -exec rm -rf "{}" \; &> /dev/null
      exit
      ;;
    destroy|disable)
      e='echo_reverse'
      ;;
    dkr)
      dkr "$@"
      exit
      ;;
    fmt)
      taho-go "$@"
      exit
      ;;
    lint)
      find . -name \*.md -exec mdl {} \;
      for name in yaml yml; do
        find . -name "*.$name" -exec yamlfmt {} \;
        find . -name "*.$name" -exec yamllint {} \;
      done
      ;;
    *)
      echo -e "${c2}'$cmd' - Unknown subcommand${c0}" >&2
      exit 1
      ;;
  esac

  # Get the enviornment code (i.e. poc, pro, dev, stg, pre, or prd)
  environment="$1"; shift  
  export TAHO_ENVIRONMENT="$environment"
  echo -e "\n* $cmd $environment"
  taho_init="$(git rev-parse --show-toplevel)/.taho.sh"
  if [ -e "$taho_init" ]; then
    source "$taho_init"
  fi

  # If running within docker, we change directory to the workspace.
  if [ -n "$TAHO_DOCKER" ]; then
    cd /workspace || exit 1
  fi

  if [[ "$1" == '-filter' ]]; then
    shift
    if [[ "$1" == '-E' ]]; then
      shift
      filter="$1"
      shift
    else
      # Without the -E we process the filter so it becomes similar to splat
      # style filter ("/" becomes "\/" and "*" becomes ".*").
      filter=".*$(
        echo "$1" |
        sed -r 's/\//\\\//g' |
        sed -r 's/\*/.*/g'
      )"
      shift
    fi
  else
    filter='.*'
  fi

  if [ -n "$TABLE_COLS" ]; then
    export TABLE_LINE='|-----|---|---|------------------------------------|---------------|-----------|'
  else
    export TABLE_LINE='|-----|---|--------------------------------------------------------------------|'
  fi

  if [ -z "$TAHO_DOCKER" ]; then
    workspace="."
  else
    workspace="$(pwd)"
  fi

  # Show header
  e='echo'
  case "$cmd" in
    check|disable|enable|ls)
      printf '|------------------------------------------------------------------------------|\n'
      if [ -n "$TAHO_ALIAS_ROOT" ]; then
        printf '|%-78s|\n' "$workspace/infrastructure/$AWS_ALIAS"
      else
        printf '|%-78s|\n' "$workspace/infrastructure"
      fi
      printf '%s\n' "$TABLE_LINE"
      if [ -n "$TABLE_COLS" ]; then
        printf '|%5s|%-3s|%-3s|%-36s|%-15s|%11s|\n' N. EN DFT UNIT MODULE REFERENCE
      else
        printf '|%5s|%-3s|%-68s|\n' N. DFT UNIT
      fi
      printf '%s\n' "$TABLE_LINE"
      ;;
  esac

  # The infrastructure may or may not be under $AWS_ALIAS
  local env_filter
  if [ -n "$TAHO_ALIAS_ROOT" ]; then
    env_filter="/$environment/"
  else
    env_filter='`'"$environment/"
  fi

  # Reads the list of units from the table in our README.
  TAHO_UNITS="$(    
    grep -E '^\|`(eu-west-2|us-east-1)' README.md |
    sed 's/^|`//' |
    sed 's/`.*//'
  )"

  TAHO_UNITS="$(
    echo "$TAHO_UNITS" |
    grep -E "$filter"
  )"

  TAHO_UNITS="$(
    echo "$TAHO_UNITS" |
    grep -F "$env_filter"
  )"

  # Start counter at zero
  n=0
  count="$(echo "$TAHO_UNITS" | wc -l)"

  # Process the command
  "$e" "$TAHO_UNITS" |
  while read -r unit; do
    n=$(( n + 1 ))
    process_unit "$n" "$count" "$cmd" "$unit" "$@"
  done

  # Show footer
  e='echo'
  case "$cmd" in
    check|disable|enable|ls)
      printf '%s\n' "$TABLE_LINE"
      ;;
  esac

  # A final line for readability
  echo
}

main "$@"
