#!/bin/bash
#
# Taho Script
#
# Executes a Taho subcommand

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck disable=SC2001
# shellcheck disable=SC2013
# shellcheck disable=SC2016
# shellcheck disable=SC2059
# shellcheck disable=SC2116
# shellcheck disable=SC2126
# shellcheck disable=SC2139

# Setup colors
c0='\033[0m'    # No color
c1='\033[0;32m' # Green
c2='\033[0;31m' # Red

# We need Terragrunt to be non interactive.
export TG_NON_INTERACTIVE=true

#######################################
# Run the aws-runas subcommand
# Arguments:
#   TBD
# Returns
#   0 if successfully, non-zero on error.
#######################################
aws_runas() {
  local aws_runas_profile="$1"; shift
  local time="$1"; shift
  if [ -z "$time" ]; then
    if [[ "$aws_runas_profile" =~ .*-pu ]]; then
      time="4h"
    elif [[ "$aws_runas_profile" =~ .*-ro ]]; then
      time="4h"
    else
      time="1h"
    fi
  fi

  echo 'unset AWS_ACCESS_KEY_ID'
  echo 'unset AWS_DEFAULT_REGION'
  echo 'unset AWS_REGION'
  echo 'unset AWS_SECRET_ACCESS_KEY'
  echo 'unset AWS_SECURITY_TOKEN'
  echo 'unset AWS_SESSION_TOKEN'
  echo ". <(aws-runas -a '$time' $aws_runas_profile)"
  echo 'aws_id="$(aws sts get-caller-identity)"'
  echo 'export AWS_SIMPLE_ROLENAME="$(echo "$aws_id" | jq -r .Arn 2>&1 | sed "s/.*assumed-role\///" | sed "s/@.*//")"'
  echo 'export AWS_ACCOUNT="$(echo "$aws_id" | jq -r .Account)"'
  echo 'export AWS_ALIAS="$(aws iam list-account-aliases | jq -r '"'"'.AccountAliases[0]'"'"')"'
}

#######################################
# Echo Reverse
# Arguments:
#   $1 - String with lines to reverse.
# Returns
#   0 if successfully, non-zero on error.
#######################################
echo_reverse() {
  local line result nl
  nl=$'\n'
  for line in $(echo "$1"); do
    result="${line}${nl}${result}"
  done
  echo "$result"
}

#######################################
# Process a unit directory
# Arguments:
#   TBD
# Returns
#   0 if successfully, non-zero on error.
#######################################
process_unit() {
  local cmd cmd1 drift enabled n unit
  n="$1"; shift
  count="$1"; shift
  cmd="$1"; shift
  unit="$1"; shift

  if [ -n "$unit" ]; then
    (
      # Set AWS REGION based on unit directory
      AWS_REGION="$(echo "$unit" | sed 's/\/.*//')"
      export AWS_REGION

      # The parent starts at the TAHO_ROOT
      local parent
      parent="${TAHO_ROOT-.}"

      # The parent may or may not be based on $AWS_ALIAS.
      if [ -z "$TAHO_NO_ALIAS_ROOT" ]; then
        parent+="/$AWS_ALIAS"
      fi

      if ! cd "$parent/$unit"; then
        echo -e "\n * ${c2}Could not change directory to '$unit'${c0}\n" >&2
        exit 1
      fi

      mkdir -p .terragrunt-cache

      # Process cmd (level 1)
      cmd1="$cmd"
      local s_k
      case "$cmd1" in
        apply)
          tfg_run 'apply' "$unit" "$@"
          ;;
        check)
          if [ -e terragrunt.hcl ]; then

            # Automatically init if needed
            terragrunt init > /dev/null 2>&1

            # Resource count bytes divided by 1024
            s_k="$(( $(terragrunt show -json 2> /dev/null | wc -c) / 1024 ))"

            if \
              terragrunt plan -detailed-exitcode -lock=false \
              > .terragrunt-cache/output 2>&1
            then
              drift='false'
            else
              drift='true'
            fi
          else
            mkdir -p .terraform

            # Automatically init if needed
            terraform init > /dev/null 2>&1

            # Resource count bytes divided by 1024
            s_k="$(( $(terraform show -json 2> /dev/null | wc -c) / 1024 ))"

            if \
              terraform plan -detailed-exitcode -lock=false \
              > .terraform/output 2>&1
            then
              drift='false'
            else
              drift='true'
            fi
          fi

          if [[ "$s_k" == '0' ]]; then
            s_k=''
          fi
          ;;
        destroy)
          tfg_destroy "$@"
          ;;
        disable)
          tg_unit_enabled "$unit" false
          cmd="$1"; shift
          if [[ "$cmd" == 'apply' ]]; then
            cmd1=''
            tfg_run 'apply' "$unit" "$@"
          fi
          ;;
        enable)
          tg_unit_enabled "$unit" true
          cmd="$1"; shift
          if [[ "$cmd" == 'apply' ]]; then
            cmd1=''
            tfg_run 'apply' "$unit" "$@"
          fi
          ;;
        init)
          if [ -z "$unit" ]; then
            tf_init "$@"
          else
            tfg_run 'init' "$unit" "$@"
          fi
          ;;
      esac

      # Process cmd (level 2)
      case "$cmd1" in
        check|disable|enable|ls)
          tfg_line "$n" "$count" "$drift" "$unit" "$s_k" "$cmd1" "$@"
          ;;
      esac
    )
  fi
}

#######################################
# Run the init subcommand
# Arguments:
#   TBD
# Returns
#   0 if successfully, non-zero on error.
#######################################
tf_init() {
  # If running within docker, we change directory to the workspace.
  if [ -n "$TAHO_DOCKER" ]; then
    cd /workspace || exit 1
  fi

  find . -name main.tf |
  sed 's/\/main.tf//' |
  while read -r module; do
    (
      cd "$module" || exit 1
      echo -e "\n * ${c1}tf init: ${c2}$module${c0}\n" >&2
      terraform init "$@"
      terraform validate
      tflint
    )
  done
}

#######################################
# Terraform or Terragrunt Destroy
# Arguments:
#   $@ - Subcommands (i.e. -upgrade, or -auto-approve)
# Returns
#   0 if successfully, non-zero on error.
#######################################
tfg_destroy() {
  echo -e "\n * tfg ${c1}destroy:${c2} $unit${c0}\n" >&2
  if [ -e terragrunt.hcl ]; then
    tg_unit_enabled "$unit" false
    terragrunt destroy "$@"
  else
    terraform destroy "$@"
  fi
}

#######################################
# Terraform or Terragrunt run
# Arguments:
#   $@ - Subcommands (i.e. -upgrade, or -auto-approve)
# Returns
#   0 if successfully, non-zero on error.
#######################################
tfg_run() {
  local cmd
  cmd="$1"; shift
  local unit="$1"; shift

  echo -e "\n * tfg ${c1}$cmd:${c2} $unit${c0}\n" >&2

  if [ -e terragrunt.hcl ]; then
    terragrunt "$cmd" "$@"
  else
    terraform "$cmd" "$@"
  fi
}

#######################################
# Show the unit enable state
# Arguments:
#   $1 - number
#   $2 - count
#   $3 - drift
#   $4 - unit
#   $5 - resource count
#   $6 - subcommand
# Returns
#   0 if successfully, non-zero on error.
#######################################
tfg_line() {
  local n="$1"; shift
  local count="$1"; shift
  local drift="$1"; shift
  local unit="$1"; shift
  local s_k="$1"; shift
  local cmd="$1"; shift

  local count_color="${c0}"
  local drift_color="${c0}"
  local enabled_color="${c0}"
  local module_color="${c0}"
  local ref_color="${c0}"
  local unit_color="${c0}"
  local dependencies_color="${c0}"
  local s_k_color="${c0}"

  local enabled
  if [ -e terragrunt.hcl ]; then
    enabled="$(
      grep -E 'unit *= ' terragrunt.hcl |
      sed 's/.*= //' |
      sed 's/ .*//'
    )"
  fi

  if [[ "$enabled" == 'true' ]]; then
    enabled_color="${c1}"
    unit_color="${c1}"
    enabled='yes'
  else
    enabled=''
  fi

  # Validate the unit
  if [[ "$cmd" != 'ls' ]]; then
    if [ -e terragrunt.hcl ]; then

      if ! terragrunt hcl validate --inputs --strict > /dev/null 2>&1; then
        note+=" terragrunt-is-not-strict"
      fi

    else

      if ! terraform validate > /dev/null 2>&1; then
        note+=" terraform-is-not-valid"
      fi

      if ! tflint > /dev/null 2>&1; then
        note+=" terraform-lint"
      fi

    fi
  fi

  if [[ "$drift" == 'true' ]]; then

    # Determine state
    local show
    if [ -e terragrunt.hcl ]; then
      if ! show="$(terragrunt show -json 2>&1)"; then
        show='terragrunt-show-error'
      fi
    else
      if ! show="$(terraform show -json 2>&1)"; then
        show='terragrunt-show-error'
      fi
    fi

    # A version only block is actually really empty
    if [[ "$show" == '{"format_version":"1.0"}' ]]; then
      show=''
    fi

    # (empty or really empty) means this is a new state.
    if [ -z "$show" ]; then
      drift='new'
    else
      drift='yes'
      drift_color="${c2}"
      enabled_color="${c2}"
      unit_color="${c2}"
    fi
  else
    drift=''
  fi

  # Track source only for teragrunt
  local source
  if [ -e terragrunt.hcl ]; then
    source="$(
      grep -F 'source =' terragrunt.hcl |
      sed 's/.*://' |
      sed 's/"//'
    )"

    local module
    module="$(
      echo "$source" |
      sed 's/^pearson-digitalandtechnology\/identity-idam-gsc-modules\/\///'
    )"

    # Trim source
    source="$(
      echo "$source" |
      sed 's/.*\/\///' |
      sed 's/\?ref=.*//'
    )"

    local ref
    ref="$(echo "$module" |
    sed 's/.*\?ref=//')"

    local behind newest_version latest_version note

    # If we have a version tag are we using the latest version?
    if [[ "$(
      find .terragrunt-cache -name .git -type d |
      tail -n 1 |
      wc -l
    )" == '1' ]]; then
      if [[ "$ref" =~ ^v[0-9].* ]]; then
        local tg_dir
        tg_dir="$(
          find .terragrunt-cache -name .git -type d |
          tail -n 1
        )"

        behind="$(
          cd "$tg_dir" || exit 1
          cd "../$source" || exit 1
          git log --oneline "$ref"..origin/main -- .| wc -l
        )"

        latest_version="$(
          cd "$tg_dir" || exit 1
          cd "../$source" || exit 1
          git describe origin/main
        )"

        if [[ "$behind" != '0' ]]; then
          ref_color="${c2}"
          if [[ "$behind" != "$latest_version" ]]; then
            note+=" behind=$behind"
          fi
        fi

        for t in $(
          cd "$tg_dir" || exit 1
          cd "../$source" || exit 1
          git tag | grep -E '^v' | sort -V -r
        )
        do
          if [[ "$(
            cd "$tg_dir" || exit 1
            cd "../$source" || exit 1
            git log --oneline "$t"..origin/main -- . | wc -l
          )" != '0' ]]; then
            break
          fi
          newest_version="$t"
        done

        if [[ "$ref" != "$newest_version" ]]; then
          note+=" newest=$newest_version"
        fi
      fi
    fi

    if [[ "$ref" == "$newest_version" ]]; then
      ref_color="${c1}"
    fi

    module="$(echo "$module" |
    sed 's/\?ref=.*//')"

    dependencies="$(
      grep -E '^dependency' terragrunt.hcl |
      sed -r 's/dependency "//' |
      sed -r 's/".*//' |
      tr '\n' ' ' |
      sed 's/ /, /g' |
      sed -r 's/, $//'
    )"
  fi

  if [ -z "$TAHO_NO_DETAIL" ]; then
    local spec=''
    spec="|${count_color}%5s${c0}|"
    spec+="${drift_color}%-3s${c0}|"
    spec+="${enabled_color}%-3s${c0}|"
    spec+="${unit_color}%-36s${c0}|"
    spec+="${module_color}%-18s${c0}|"
    spec+="${ref_color}%11s${c0}|"
    spec+="${dependencies_color}%-30s${c0}|"
    spec+="${s_k_color}%5s${c0}|"
    spec+="$note\n"

    printf "$spec" "$n/$count" "$drift" "$enabled" "$unit" "$module" "$ref" \
      "$dependencies" \
      "$s_k"
  else
    local spec=''
    spec="|${count_color}%5s${c0}|"
    spec+="${drift_color}%-3s${c0}|"
    spec+="${unit_color}%-102s${c0}|"
    spec+="${s_k_color}%5s${c0}|"
    spec+="$note\n"

    printf "$spec" "$n/$count" "$drift" "$unit" "$s_k"
  fi
}

#######################################
# Set the unit enable state
# Arguments:
#   $1 Unit path
#   $2 Value (true or false)
# Returns
#   0 if successfully, non-zero on error.
#######################################
tg_unit_enabled() {
  local unit="$1"; shift
  local enabled="$1"; shift

  local sed_cfg
  sed_cfg="s/ *unit * = \{ enabled = .* \}/unit = { enabled = $enabled }/g"

  sed -i -r "$sed_cfg" terragrunt.hcl;
  taho fmt > /dev/null
}

#######################################
# Main function
# Arguments:
#   $@ Subcommand (i.e. check, destroy, disable, or enable)
# Returns
#   0 if successfully, non-zero on error.
#######################################
main() {
  if [ -z "$TAHO_HOME" ]; then
    # shellcheck disable=SC2012
    TAHO_HOME="$(
      ls -lap "$(which taho)" |
      sed 's/.*> //' |
      sed 's/\/script$//'
    )"
  fi
  export TAHO_HOME

  # Make sure that .tmp exists.
  mkdir -p "$(git rev-parse --show-toplevel)/.tmp"

  # Parse the subcommand
  local cmd
  cmd="${1:-shell}"; shift
  if [[ "$cmd" == 'install' ]]; then
    rm -rf /usr/local/bin/taho
    ln -s "$PWD/script" /usr/local/bin/taho
    go install
    echo 'Installed taho'
    exit
  fi

  # Process subcommand (top level)
  local e environment filter n
  case "$cmd" in
    -v)
      taho-go -v
      exit
      ;;
    apply|check|enable|init|ls)
      e='echo'
      ;;
    aws-runas)
      aws_runas "$@"
      ;;
    clean)
      cd "$(git rev-parse --show-toplevel)" || exit 1
      find . -name .terraform -type d -exec rm -rf {} \; &> /dev/null
      find . -name .terragrunt-cache -type d -exec rm -rf {} \; &> /dev/null
      if [[ "$1" == '-unlock' ]]; then
        shift
        find . -name .terraform.lock.hcl -type f -delete &> /dev/null
      fi
      exit
      ;;
    destroy|disable)
      e='echo_reverse'
      ;;
    fmt)
      taho-go "$@"
      exit
      ;;
    tf-init)
      e='echo'
      tf_init "$@"
      ;;
    lint)
      find . -name \*.md -exec mdl {} \;
      for name in yaml yml; do
        find . -name "*.$name" -exec yamlfmt {} \;
        find . -name "*.$name" -exec yamllint {} \;
      done
      tf_init "$@"
      ;;
    shell)
      shell "$@"
      exit
      ;;
    start)
      start "$@"
      ;;
    *)
      shell "$cmd"
      exit 1
      ;;
  esac

  # Get the enviornment code (i.e. poc, pro, dev, stg, pre, or prd)
  environment="$1"; shift
  if [ -z "$environment" ]; then
    exit
  fi

  export TAHO_ENVIRONMENT="$environment"
  echo -e "\n${c1} * $cmd:${c2} $environment${c0}\n" >&2
  taho_init="$(git rev-parse --show-toplevel)/.taho.sh"
  if [ -e "$taho_init" ]; then
    source "$taho_init"
  fi

  # If running within docker, we change to the workspace directory.
  if [ -n "$TAHO_DOCKER" ]; then
    cd /workspace || exit 1
  fi

  if [[ "$1" == '-filter' ]]; then
    shift
    filter="$1"
    shift
  else
    filter='.*'
  fi

  if [ -z "$TAHO_NO_DETAIL" ]; then
    export TABLE_LINE='|-----|---|---|------------------------------------|------------------|-----------|------------------------------|-----|'
  else
    export TABLE_LINE='|-----|---|------------------------------------------------------------------------------------------------------|-----|'
  fi

  if [ -z "$TAHO_DOCKER" ]; then
    workspace="."
  else
    workspace="$(pwd)"
  fi

  # Show header
  e='echo'
  case "$cmd" in
    check|disable|enable|ls)
      printf '|----------------------------------------------------------------------------------------------------------------------|\n'
      local base="$workspace"
      if [ -n "$TAHO_ROOT" ]; then
        base+="/$TAHO_ROOT"
      fi
      if [ -z "$TAHO_NO_ALIAS_ROOT" ]; then
        printf '|%-118s|\n' "$base/$AWS_ALIAS"
      else
        printf '|%-118s|\n' "$base"
      fi
      printf '%s\n' "$TABLE_LINE"
      if [ -z "$TAHO_NO_DETAIL" ]; then
        printf '|%5s|%-3s|%-3s|%-36s|%-18s|%11s|%-30s|%5s|\n' N. DFT EN UNIT MODULE REFERENCE DEPENDENCIES 'S (k)'
      else
        printf '|%5s|%-3s|%-102s|%5s|\n' N. DFT UNIT 'S (k)'
      fi
      printf '%s\n' "$TABLE_LINE"
      ;;
  esac

  # The infrastructure may or may not be under $AWS_ALIAS
  local env_filter
  if [ -z "$TAHO_NO_ALIAS_ROOT" ]; then
    env_filter="/$environment/"
  else
    env_filter="${TAHO_ENV_FILTER_PREFIX}$environment/"
  fi

  # Reads the list of units from the table in our README.
  if [ -z "$TAHO_REGX" ]; then
    TAHO_REGX='(eu-west-2|us-east-1)'
  fi
  local regx="^\|\`$TAHO_REGX/"
  TAHO_UNITS="$(
    grep -E "$regx" "$(git rev-parse --show-toplevel)/README.md" |
    sed 's/^|`//' |
    sed 's/`.*//'
  )"

  TAHO_UNITS="$(
    echo "$TAHO_UNITS" |
    grep -E "$filter"
  )"

  TAHO_UNITS="$(
    echo "$TAHO_UNITS" |
    grep -F "$env_filter"
  )"

  # Start counter at zero
  n=0
  count="$(echo "$TAHO_UNITS" | wc -l)"

  # Process the subcommand
  "$e" "$TAHO_UNITS" |
  while read -r unit; do
    n=$(( n + 1 ))
    process_unit "$n" "$count" "$cmd" "$unit" "$@"
  done

  # Show footer
  e='echo'
  case "$cmd" in
    check|disable|enable|ls)
      printf '%s\n' "$TABLE_LINE"
      ;;
  esac

  # A final line for readability
  echo
}

#######################################
# Run the Console subcommand
# Arguments:
#   TBD
# Returns
#   0 if successfully, non-zero on error.
#######################################
shell() {
  local taho_id
  taho_id="$(uuidgen)"

  # Use linux/amd64
  export DOCKER_DEFAULT_PLATFORM='linux/amd64'

  # Capture the current working directory
  local working_dir="$PWD"

  # Change directory to toplevel
  cd "$(git rev-parse --show-toplevel)" || exit 1

  # Build
  if [[ "$1" == '-V' ]]; then
    export TAHO_VERBOSE=true
    shift
  fi
  (
    cd "$TAHO_HOME" || exit 1
    db="docker build . -t taho"
    if [ -z "$TAHO_VERBOSE" ]; then
      db+=' > /dev/null 2>&1'
    fi
    eval "$db"
  )

  (
    echo $'#!/bin/bash\n'
    echo "cd '.$(
      echo "$working_dir" |
      sed 's/'"$(
        pwd |
        sed 's/\//\\\//g'
      )"'//'
    )'"
    echo 'export PATH="$HOME/.tfenv/bin:$PATH"'
    echo 'export PATH="$HOME/.tgenv/bin:$PATH"'
    echo 'export PATH="$HOME/go/bin:$PATH"'
    if [ -z "$1" ]; then
      echo 'bash'
    else
      echo "bash -c 'source /root/.bashrc; $*'"
    fi
  ) > ".tmp/start-$taho_id"
  chmod +x ".tmp/start-$taho_id"

  # Ensure that required file system resources exist.
  existing_or "$HOME/.cache/pre-commit"         'mkdir -p'
  existing_or "$HOME/.terraform.d/plugin-cache" 'mkdir -p'
  existing_or "$HOME/.terraformrc"              'touch'
  existing_or "$PWD/.tmp/history"               'touch'

  # Create a docker subcommand
  local d
  d='time docker run --rm -it'
  d+=' -e TAHO_DOCKER=true'
  d+=" -h '$(basename "$PWD")'"
  d+=" -v '$HOME/.ssh:/root/.ssh'"
  d+=" -v '$PWD:/workspace'"
  d+=" -v '$PWD/.tmp/history:/root/.history:rw'"

  # Add volume mounts to the docker subcommand
  for x in \
    '.cache/pre-commit' \
    '.ssh/known_hosts' \
    '.gitconfig'
  do
    d+=" -v '$HOME/$x:/root/$x'"
  done

  # Add rw volume mounts to the docker subcommand
  for x in \
    '.terraform.d/plugin-cache' \
    '.terraformrc' \
    '.aws'
  do
    d+=" -v '$HOME/$x:/root/$x:rw'"
  done

  # Add environment variables to the docker subcommand
  for v in $(
    env |
    grep -E '^(AWS_)' |
    sed 's/=.*//' \
  ); do
    d+=" -e $v"
  done

  # Evaluate the docker subcommand
  eval "$d taho './.tmp/start-$taho_id'"
  rm "./.tmp/start-$taho_id"
}

# Define a function for exist or evaluate
existing_or() {
  [ -e "$1" ] || eval "$2 $1"
}

#######################################
# Run the start subcommand
# Arguments:
#   TBD
# Returns
#   0 if successfully, non-zero on error.
#######################################
start() {
  echo "alias taho-aws-x='(rm -rf ~/.aws/.aws_saml_* > /dev/null) > /dev/null 2>&1'"

  for profile in $(grep -F '[profile ' < "$HOME/.aws/config" |
    sed 's/.* //' |
    sed 's/\]//'
  ); do
    echo "alias \"taho-aws-$profile\"=\". <(taho aws-runas $profile)\""
  done

  if [[ "$(uname)" == 'Darwin' ]]; then
    echo "alias tgap='git add -p'"
    echo "alias tgca='git commit --amend'"
    echo "alias tgph='git push -u origin HEAD'"
    echo "alias tgpo='git push origin'"
    echo "alias tgru='git remote update'"
    echo "alias tgst='git status'"
    echo "alias tgwi='git commit -m wip'"
    echo "alias tgrm='git rebase -i -- origin/main'"

    echo "tgcm() {"
    echo "  local prefix"
    echo "  prefix=\$(git branch --show-current | tr '[:lower:]' '[:upper:]')"
    echo "  if [[ \"\$prefix\" == 'MAIN' ]]; then"
    echo "    prefix=''"
    echo "  fi"
   echo "   [ -z \"\$prefix\" ] || prefix+=' '"
    echo "  git commit -m\"\$prefix\$1\" && git commit --amend"
    echo "}"
  fi

  if [ -e .taho.sh ]; then
    source .taho.sh
  fi

  echo "$TAHO_ALIASES"
}

main "$@"
