#!/bin/bash
# shellcheck disable=SC2005

if ! grep '^func ' < main.go | sort -c; then
  >&2 echo "ERROR: Functions are not in sorted order."
  >&2 echo "**********"
  >&2 echo "$(grep '^func ' < main.go 2>&1 | nl 2>&1   | sed -e 's/^/ACTUAL --- /')"
  >&2 echo "**********"
  >&2 echo "$(grep '^func ' < main.go 2>&1 | sort | nl 2>&1 | sed -e 's/^/EXPECTED - /')"
  >&2 echo "**********"
  exit 1
fi
