#!/bin/bash
set -e

do/check-go-sort

status="$(git status -s)"
if [ -n "$status" ]; then
  >&2 echo "ERROR: Unable to release due to git status."
  >&2 echo "$status"
  exit 1
fi

rm -rf release
mkdir release

go install

v="v$(taho -v)"
git tag -f -s -m "$v" "$v"

for os in linux darwin; do
  for arch in amd64 arm64; do
    env GOOS="$os" GOARCH="$arch" go build .
    mv taho "release/taho-$v-$os-$arch"
  done
done
