#!/bin/bash
# shellcheck disable=SC2048
# shellcheck disable=SC2086

main() {
  rm -f "$HOME/go/bin/taho"
  go install .

  if [ -d tests ]; then
    cd tests || exit 1
  fi

  test "$1" 00 67e3f7ab39e5ecca9df22c044cac279836f75922
  test "$1" 01 91268ce3a9f4edb082291f5283ecce8fdf6c71d0
  test "$1" 02 44373f9b0b1095d02c744f1a9b9e7e7f8995bdb4
  test "$1" 03 6422ff9a0533e512f26a33241ec8366266b307bb
  test "$1" 04 8525389041f324edd6850012b7c5f640f2a04906
  test "$1" 05 88c1a8f8f8f6a38562f0af0f97690c524e8dd533
  test "$1" 06 5623700e77b64f571fc189e02124f06a3d874b91
  test "$1" 07 76d6aa2652bfadf456872703bc5c7603f2ca5f0c
  test "$1" 08 0197b75701503467e7a2b45ed61dbd9705498131
  test "$1" 09 685158988340fdfe0111d6d04d3608c9536c6025
  test "$1" 10 8822136238078d2c63554554110f12467faa0062
  test "$1" 11 54e34671a0523e9fdb40a1b561744254f16595b8
  test "$1" 12 5d56eb85084521957d5de1fd7ae0388b3b88fe30
  test "$1" 13 e9a31804aaa1085f4a3009a190ec3d52625e16ca
}

test() {
  expected="$3"
  (
    rm -rf "$2/result"
    cp -r "$2" result
    mv result "$2"
    cd "$2/result" || exit 1

    if [[ "$1" == 'setup' ]]; then
      echo "Test $2: Setup Complete"
    else
      taho 2>&1 | sed "s/^/Test $2: /"
      echo ''

      result1="$(
        (
          [ ! -e ./main.tfvars ] || sha1sum ./*.tfvars
          [ ! -e ./main.tf ] || sha1sum ./*.tf
          [ ! -e ./README.md ] || sha1sum ./*.md
        ) |
        sha1sum |
        sed 's/ .*//'
      )"

      if [[ "$expected" != "$result1" ]]; then
        >&2 echo "Test $2 failed; got $result1"
        exit 1
      fi

      result2="$(
        (
          [ ! -e ./main.tfvars ] || sha1sum ./*.tfvars
          [ ! -e ./main.tf ] || sha1sum ./*.tf
          [ ! -e ./README.md ] || sha1sum ./*.md
        ) |
        sha1sum |
        sed 's/ .*//'
      )"

      if [[ "$result1" != "$result2" ]]; then
        >&2 echo "Test $1 failed because result1 != result2"
        exit 1
      fi
    fi
  ) || exit 1

  rm -rf test
}

main $*